# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-27 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='cate')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='pub_date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='up_date')),
                ('content', models.DateField(blank=True, null=True, verbose_name='content')),
            ],
            options={
                'ordering': ['-pub_date'],
                'db_table': 't_article',
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
    ]
